In [1]:
import tensorflow as tf
from tensorflow import keras
import pickle as pkl
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('./data/Processed_file.csv')
df

gender  SeniorCitizen  Partner  Dependents    tenure  PhoneService  \
0          0              0        1           0  0.000000             0   
1          1              0        0           0  0.464789             1   
2          1              0        0           0  0.014085             1   
3          1              0        0           0  0.619718             0   
4          0              0        0           0  0.014085             1   
...      ...            ...      ...         ...       ...           ...   
7027       1              0        1           1  0.323944             1   
7028       0              0        1           1  1.000000             1   
7029       0              0        1           1  0.140845             0   
7030       1              1        1           0  0.042254             1   
7031       1              0        0           0  0.915493             1   

      MultipleLines  OnlineSecurity  OnlineBackup  DeviceProtection  ...  \
0                 0               0             1                 0  ...   
1                 0               1             0                 1  ...   
2                 0               1             1                 0  ...   
3                 0               1             0                 1  ...   
4                 0               0             0                 0  ...   
...             ...             ...           ...               ...  ...   
7027              1               1             0                 1  ...   
7028              1               0             1                 1  ...   
7029              0               1             0                 0  ...   
7030              1               0             0                 0  ...   
7031              0               1             0                 1  ...   

      InternetService_DSL  InternetService_Fiber optic  InternetService_No  \
0                       1                            0                   0   
1                       1                            0                   0   
2                       1                            0                   0   
3                       1                            0                   0   
4                       0                            1                   0   
...                   ...                          ...                 ...   
7027                    1                            0                   0   
7028                    0                            1                   0   
7029                    1                            0                   0   
7030                    0                            1                   0   
7031                    0                            1                   0   

      Contract_Month-to-month  Contract_One year  Contract_Two year  \
0                           1                  0                  0   
1                           0                  1                  0   
2                           1                  0                  0   
3                           0                  1                  0   
4                           1                  0                  0   
...                       ...                ...                ...   
7027                        0                  1                  0   
7028                        0                  1                  0   
7029                        1                  0                  0   
7030                        1                  0                  0   
7031                        0                  0                  1   

      PaymentMethod_Bank transfer (automatic)  \
0                                           0   
1                                           0   
2                                           0   
3                                           1   
4                                           0   
...                                       ...   
7027                                        0  

In [3]:
x  = df.drop('Churn',axis='columns')
y= df['Churn']
x.shape

(7032, 26)

In [4]:
y.shape

(7032,)

In [5]:
x_train,x_test,y_train,y_test  = train_test_split(x,y,test_size=0.2,random_state=5)

In [6]:
len(x_train)

5625

In [7]:
model = keras.Sequential([
    keras.layers.Dense(300,input_shape=(26,),activation='relu'),
    keras.layers.Dense(100,activation='relu'),
    keras.layers.Dense(50,activation='relu'),
    keras.layers.Dense(1,activation='sigmoid')
])


In [8]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [9]:
model.fit(x_train,y_train,epochs=10)

Epoch 1/10
176/176 [==============================] - 7s 23ms/step - loss: 0.4415 - accuracy: 0.7886
Epoch 2/10
176/176 [==============================] - 11s 63ms/step - loss: 0.4142 - accuracy: 0.8023
Epoch 3/10
176/176 [==============================] - 10s 59ms/step - loss: 0.4122 - accuracy: 0.8062
Epoch 4/10
176/176 [==============================] - 9s 53ms/step - loss: 0.4029 - accuracy: 0.8103
Epoch 5/10
176/176 [==============================] - 8s 48ms/step - loss: 0.3995 - accuracy: 0.8105
Epoch 6/10
176/176 [==============================] - 7s 41ms/step - loss: 0.3984 - accuracy: 0.8140
Epoch 7/10
176/176 [==============================] - 6s 36ms/step - loss: 0.3917 - accuracy: 0.8188
Epoch 8/10
176/176 [==============================] - 6s 35ms/step - loss: 0.3828 - accuracy: 0.8238
Epoch 9/10
176/176 [==============================] - 7s 42ms/step - loss: 0.3803 - accuracy: 0.8196
Epoch 10/10
176/176 [==============================] - 7s 42ms/step - loss: 0.3737 - accu

In [10]:
model.evaluate(x_test,y_test)

44/44 [==============================] - 1s 23ms/step - loss: 0.4651 - accuracy: 0.7719


[0.4650786519050598, 0.7718549966812134]

In [11]:
y_pred= model.predict(x_test)
y_pred

array([[0.22610813],
       [0.43207026],
       [0.00630605],
       ...,
       [0.56286144],
       [0.6565724 ],
       [0.7423256 ]], dtype=float32)

In [12]:
y_pred.shape

(1407, 1)

In [13]:
y_pred.reshape(1407)

array([0.22610813, 0.43207026, 0.00630605, ..., 0.56286144, 0.6565724 ,
       0.7423256 ], dtype=float32)

In [14]:
new_pred =[]
for churn in y_pred:
    if churn>0.5:
        new_pred.append(1)
    else:
        new_pred.append(0)


In [15]:
new_pred[:5]

[0, 0, 0, 1, 0]

In [16]:
y_test[:5]

2655    0
743     0
5570    1
64      1
3282    1
Name: Churn, dtype: int64

## Classification Report
    Precision
let's say there are 2 class Yes and No.
So precision will be the amount of correctly predicted classes.
Assuming Yes was correctly predicted 300 times and wrongly predicted 100 times
so the precision for Yes will 300/(300+100) vice-versa for No class as well

    Recall
Truth 0 predicted 1<br>
Truth is 1 predicted 0<br>
how many times they have predicted 

In [17]:
from sklearn.metrics import confusion_matrix, classification_report
classification_report(y_test,new_pred)

'              precision    recall  f1-score   support\n\n           0       0.80      0.91      0.85       999\n           1       0.66      0.43      0.52       408\n\n    accuracy                           0.77      1407\n   macro avg       0.73      0.67      0.69      1407\nweighted avg       0.76      0.77      0.76      1407\n'

In [18]:
print(classification_report(y_test,new_pred))

              precision    recall  f1-score   support

           0       0.80      0.91      0.85       999
           1       0.66      0.43      0.52       408

    accuracy                           0.77      1407
   macro avg       0.73      0.67      0.69      1407
weighted avg       0.76      0.77      0.76      1407



In [19]:
cm = tf.math.confusion_matrix(labels= y_test,predictions=new_pred)
cm

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[910,  89],
       [232, 176]])>

In [20]:
910/(910+232)

0.7968476357267951